sudo: required
services:
  - docker

before_install:
  - docker build -t conradpacesa/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run conradpacesa/react-test npm test -- --coverage

after_success:
  - docker build -t conradpacesa/multi-client ./client
  - docker build -t conradpacesa/multi-nginx ./nginx
  - docker build -t conradpacesa/multi-server ./server
  - docker build -t conradpacesa/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push conradpacesa/multi-client
  - docker push conradpacesa/multi-nginx
  - docker push conradpacesa/multi-server
  - docker push conradpacesa/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ca-central-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ca-central-1-391859427221
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY